### ISSUE TITLE
install fails on Windows 10

### ISSUE THREAD

**Issue by olevine** [coralproject/talk-install#3]
I'm trying to install Talk on Heroku using talk-install from my Windows 10 machine at the International Center for Journalists.  I'm running the installation locally on port 3000. 
The installation fails with this message. Appreciate any guidance here. Thanks!

build failed

-----> Node.js app detected

-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=false
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true

-----> Installing binaries
       engines.node (package.json):  ^7.8.0
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version ^7.8.0 via semver.io...
       Downloading and installing node 7.10.0...
       Using default npm version: 4.2.0
       Resolving yarn version (latest) via semver.io...
       Downloading and installing yarn (0.24.5)...
       Installed yarn 0.24.5

-----> Restoring cache
       Skipping cache restore (new-signature)

-----> Building dependencies
       Installing node modules (yarn.lock)
       yarn install v0.24.5
       [1/4] Resolving packages...
       [2/4] Fetching packages...
       warning fsevents@1.1.1: The platform "linux" is incompatible with this module.
       info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
       [3/4] Linking dependencies...
       [4/4] Building fresh packages...
       $ ./bin/cli plugins reconcile --skip-remote
       /tmp/build_b2af81d55265e2fd1f3f00efc34bc143/coralproject-talk-5168f56/node_modules/env-rewrite/src/rewriter.js:24
       throw new Error('Env ' + oldEnvName + ' was not defined');
       ^
       
       Error: Env PORT was not defined
       at Object.keys.forEach.newEnvName (/tmp/build_b2af81d55265e2fd1f3f00efc34bc143/coralproject-talk-5168f56/node_modules/env-rewrite/src/rewriter.js:24:19)
       at Array.forEach (native)
       at Object.module.exports [as rewrite] (/tmp/build_b2af81d55265e2fd1f3f00efc34bc143/coralproject-talk-5168f56/node_modules/env-rewrite/src/rewriter.js:19:26)
       at Object.<anonymous> (/tmp/build_b2af81d55265e2fd1f3f00efc34bc143/coralproject-talk-5168f56/bin/commander.js:9:24)
       at Module._compile (module.js:571:32)
       at Object.Module._extensions..js (module.js:580:10)
       at Module.load (module.js:488:32)
       at tryModuleLoad (module.js:447:12)
       at Function.Module._load (module.js:439:3)
       at Module.require (module.js:498:17)
       error Command failed with exit code 1.
       info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - This project was built with yarn, which is new and under development. Some projects can still be built more reliably with npm
       https://devcenter.heroku.com/articles/nodejs-support#build-behavior
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.

 !     Push failed

**Comment by wyattjoh** [comment]
Hi @olevine! What version of Talk were you trying to install?

**Comment by olevine** [comment]
Thanks. Installer was installing version 1.8.0. I updated npm, tried again, and the installation succeeded.

**Comment by wyattjoh** [comment]
Odd! Let me know if the issue persists. I'll be pushing a patch which should update some things as well.
